title: Proxy Tech Support
description: Job Support & Interview Proxy for IT Professionals
url: https://proxytechsupport.com

markdown: kramdown
permalink: /blog/:title/

collections:
  interviews:
    output: true
    permalink: /interviews/:name/

plugins:
  - jekyll-sitemap
